export const pricing = [
  {
    pricingTitle: 'Business Servers Pricing',
    pricingPlans: [
      {
        plan: 'Basic',
        valueMonth: '80',
        initialSetup: '300',
        themedCustom: '200',
        botIntegration: '150',
        sectorTools: '180',
        fullPrice: '830',
        borderColor: 'border-imperial',
        textColor: 'text-imperial',
        hoverBg: 'hover:bg-imperial',
      },
      {
        plan: 'Standart',
        valueMonth: '150',
        initialSetup: '600',
        themedCustom: '400',
        botIntegration: '350',
        sectorTools: '400',
        fullPrice: '1.750',
        borderColor: 'border-neon',
        textColor: 'text-neon',
        hoverBg: 'hover:bg-neon',
      },
      {
        plan: 'Premiun',
        valueMonth: '300',
        initialSetup: '1.200',
        themedCustom: '800',
        botIntegration: '700',
        sectorTools: '750',
        fullPrice: '3.450',
        borderColor: 'border-hunyadi',
        textColor: 'text-hunyadi',
        hoverBg: 'hover:bg-hunyadi',
      },
    ],
  },
  {
    pricingTitle: 'Schools Servers Pricing',
    pricingPlans: [
      {
        plan: 'Basic',
        valueMonth: '50',
        initialSetup: '200',
        themedCustom: '150',
        botIntegration: '100',
        sectorTools: '120',
        fullPrice: '570',
        borderColor: 'border-imperial',
        textColor: 'text-imperial',
        hoverBg: 'hover:bg-imperial',
      },
      {
        plan: 'Standart',
        valueMonth: '100',
        initialSetup: '400',
        themedCustom: '300',
        botIntegration: '250',
        sectorTools: '280',
        fullPrice: '1.230',
        borderColor: 'border-neon',
        textColor: 'text-neon',
        hoverBg: 'hover:bg-neon',
      },
      {
        plan: 'Premiun',
        valueMonth: '200',
        initialSetup: '800',
        themedCustom: '600',
        botIntegration: '500',
        sectorTools: '550',
        fullPrice: '2.450',
        borderColor: 'border-hunyadi',
        textColor: 'text-hunyadi',
        hoverBg: 'hover:bg-hunyadi',
      },
    ],
  },
  {
    pricingTitle: 'Gaming Servers Pricing',
    pricingPlans: [
      {
        plan: 'Basic',
        valueMonth: '60',
        initialSetup: '250',
        themedCustom: '180',
        botIntegration: '120',
        sectorTools: '150',
        fullPrice: '700',
        borderColor: 'border-imperial',
        textColor: 'text-imperial',
        hoverBg: 'hover:bg-imperial',
      },
      {
        plan: 'Standart',
        valueMonth: '120',
        initialSetup: '500',
        themedCustom: '350',
        botIntegration: '280',
        sectorTools: '350',
        fullPrice: '1.480',
        borderColor: 'border-neon',
        textColor: 'text-neon',
        hoverBg: 'hover:bg-neon',
      },
      {
        plan: 'Premiun',
        valueMonth: '250',
        initialSetup: '1.000',
        themedCustom: '700',
        botIntegration: '550',
        sectorTools: '600',
        fullPrice: '2.850',
        borderColor: 'border-hunyadi',
        textColor: 'text-hunyadi',
        hoverBg: 'hover:bg-hunyadi',
      },
    ],
  },
];
